version: "2"
services:
    php-cli:
        image: lojassimonetti/php-apache-oci8-composer:php${PHP_VERSION:-8dot1}
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            - http_proxy=${http_proxy:-}
            - no_proxy=${no_proxy:-}
