name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run:
    strategy:
      matrix:
        php-version: ["php7dot4"]
        composer-flags: ["", "--prefer-lowest"]
        include:
          - php-version: "php8dot1"
            composer-flags: ""
    runs-on: ubuntu-latest
    container:
      image: lojassimonetti/php-apache-oci8-composer:${{ matrix.php-version }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: composer update ${{ matrix.composer-flags }} -o --no-scripts
      - run: php ./vendor/bin/phpunit -c phpunit.xml.dist
