name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run:
    strategy:
      matrix:
        php-version: ["php7dot4", "php8dot1"]
    runs-on: ubuntu-latest
    container:
      image: lojassimonetti/php-apache-oci8-composer:${{ matrix.php-version }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: echo ${{ matrix.version }}
      - run: composer install -o --no-scripts
      - run: php ./vendor/bin/phpunit -c phpunit.xml.dist
